from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml


class ConfigError(ValueError):
    """Raised when a VFO group profile is invalid."""


@dataclass(frozen=True)
class ChannelConfig:
    id: str
    frequency_hz: int
    mode: str
    enabled: bool = True
    sink: str | None = None


@dataclass(frozen=True)
class GroupConfig:
    group_id: str
    radio: str
    sample_rate: int
    base_ssrc: int
    base_port: int
    channels: tuple[ChannelConfig, ...]

    @property
    def enabled_channels(self) -> tuple[ChannelConfig, ...]:
        return tuple(channel for channel in self.channels if channel.enabled)

    def to_legacy_shell(self) -> str:
        lines = [
            "# Generated by ka9q-vfo-group from YAML. Do not edit.",
            f'HOST={_shell_quote(self.radio)}',
            f"RATE={self.sample_rate}",
            f"BASE_SSRC={self.base_ssrc}",
            f"BASE_PORT={self.base_port}",
            "RADIO_CHANNELS=(",
        ]
        for channel in self.enabled_channels:
            lines.append(
                f'    {_shell_quote(f"{channel.id} {channel.frequency_hz} {channel.mode}")}'
            )
        lines.append(")")
        lines.append("")
        return "\n".join(lines)


def load_group_config(path: str | Path, *, expected_group_id: str | None = None) -> GroupConfig:
    profile_path = Path(path)
    try:
        raw = yaml.safe_load(profile_path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise ConfigError(f"Configuration file not found: {profile_path}") from exc
    except yaml.YAMLError as exc:
        raise ConfigError(f"Invalid YAML in {profile_path}: {exc}") from exc

    if not isinstance(raw, dict):
        raise ConfigError("Profile root must be a mapping")

    group = _mapping(raw.get("group"), "group")
    allocation = _mapping(raw.get("allocation"), "allocation")
    channels_raw = raw.get("channels")
    if not isinstance(channels_raw, list) or not channels_raw:
        raise ConfigError("channels must be a non-empty list")

    group_id = _string(group.get("id"), "group.id")
    if expected_group_id and group_id != expected_group_id:
        raise ConfigError(
            f"group.id must match requested group: expected {expected_group_id!r}, got {group_id!r}"
        )
    _validate_identifier(group_id, "group.id")

    radio = _string(group.get("radio"), "group.radio")
    sample_rate = _positive_int(group.get("sample_rate"), "group.sample_rate")
    base_ssrc = _positive_int(allocation.get("base_ssrc"), "allocation.base_ssrc")
    base_port = _port(allocation.get("base_port"), "allocation.base_port")

    channels: list[ChannelConfig] = []
    seen_ids: set[str] = set()
    seen_sinks: set[str] = set()
    for index, item in enumerate(channels_raw):
        entry = _mapping(item, f"channels[{index}]")
        channel_id = _string(entry.get("id"), f"channels[{index}].id")
        _validate_identifier(channel_id, f"channels[{index}].id")
        if channel_id in seen_ids:
            raise ConfigError(f"duplicate channel id: {channel_id}")
        seen_ids.add(channel_id)

        enabled = entry.get("enabled", True)
        if not isinstance(enabled, bool):
            raise ConfigError(f"channels[{index}].enabled must be true or false")

        frequency_hz = _positive_int(entry.get("frequency_hz"), f"channels[{index}].frequency_hz")
        mode = _string(entry.get("mode"), f"channels[{index}].mode").lower()
        if mode not in {"usb", "lsb", "am", "fm", "cw", "cwr", "iq"}:
            raise ConfigError(f"channels[{index}].mode is unsupported: {mode}")

        expected_sink = f"vc_{group_id}_{channel_id}"
        sink_value = entry.get("sink")
        sink = None if sink_value is None else _string(sink_value, f"channels[{index}].sink")
        if sink and sink != expected_sink:
            raise ConfigError(
                f"channels[{index}].sink must be {expected_sink!r} for the current controller"
            )
        sink = expected_sink
        if sink in seen_sinks:
            raise ConfigError(f"duplicate sink: {sink}")
        seen_sinks.add(sink)

        channels.append(
            ChannelConfig(
                id=channel_id,
                frequency_hz=frequency_hz,
                mode=mode,
                enabled=enabled,
                sink=sink,
            )
        )

    enabled_count = sum(channel.enabled for channel in channels)
    if enabled_count == 0:
        raise ConfigError("at least one channel must be enabled")
    if base_port + enabled_count - 1 > 65535:
        raise ConfigError("allocated rigctld ports exceed 65535")
    if base_ssrc + enabled_count - 1 > 0xFFFFFFFF:
        raise ConfigError("allocated SSRC values exceed uint32 range")

    return GroupConfig(
        group_id=group_id,
        radio=radio,
        sample_rate=sample_rate,
        base_ssrc=base_ssrc,
        base_port=base_port,
        channels=tuple(channels),
    )


def _mapping(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ConfigError(f"{field} must be a mapping")
    return value


def _string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{field} must be a non-empty string")
    return value.strip()


def _positive_int(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        raise ConfigError(f"{field} must be a positive integer")
    return value


def _port(value: Any, field: str) -> int:
    port = _positive_int(value, field)
    if port > 65535:
        raise ConfigError(f"{field} must be between 1 and 65535")
    return port


def _validate_identifier(value: str, field: str) -> None:
    if not all(char.isalnum() or char in "_-" for char in value):
        raise ConfigError(f"{field} may contain only letters, numbers, underscore and dash")


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"
